services:  
  documentation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: documentation
    restart: unless-stopped
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.documentation.rule=Host(`assistia.martinameunier.fr`)"
      - "traefik.http.routers.documentation.entrypoints=websecure"
      - "traefik.http.routers.documentation.tls=true"
      - "traefik.http.routers.documentation.tls.certresolver=myresolver"

      - "traefik.http.services.documentation.loadbalancer.server.port=80"

    networks:
      - web

networks:
  web:
    name: web